### ISSUE TITLE
Spaces not correctly interpreted, Program too slow for use

### ISSUE THREAD

**Issue by DataandGoliath** [thelinuxchoice/instashell#1]
I attempted to use this program with Kali Linux 2018.1. Running it with a test list, passwords such as
This Is A Password
were tried word by word, rather than line by line. This meant that a known valid password reported no success, because it was tried part by part rather than as a whole. (i.e.,
Trying: This
Trying: Is
Trying: A
Trying: Password
instead of
Trying: This Is A Password)
Also, this program takes far too long to complete an attack, rendering it nearly useless in the advent of multi-threaded crackers. 
Please rectify this in a future release.

**Comment by thelinuxchoice** [comment]
Thanks for your feedback, the password issue was fixed.
