### ISSUE TITLE
Tool alerts target upon found login

### ISSUE THREAD

**Issue by DataandGoliath** [thelinuxchoice/instashell#2]
Due to the nature of Tor, login requests appear to originate from locations all around the world.
This program, when attempting to log in, if it finds a valid login, has its foreign IP address logged.
This means that when the legitimate user logs in, they will be prompted with a message such as 
"Is this you? We detected a suspicious login from Peru. <Yes this was me> <No this wasn't me>" Which allows them to realize an account breach has occurred and change their password, and possibly add, for example, 2FA - rendering the brute at best pointless, and at worst detrimental to account breach.

Suggested fix: IP geolocation filtering - allow user to select a general area and change exit policies to only allow exit nodes from set location.

**Comment by thelinuxchoice** [comment]
You can do that changing your ExitNode... add to /etc/tor/torrc file:
ExitNode {us}
