### ISSUE TITLE
 line 149: kill: (29431) - No such process

### ISSUE THREAD

**Issue by blunts1498** [thelinuxchoice/instashell#4]
I'm trying this and it has stopped working. It tells me password found but the password isn't it. Any ideas?

./instashell.sh: line 149: kill: (29431) - No such process

**Comment by thelinuxchoice** [comment]
@blunts1498 This bug was fixed, can you try again?

**Comment by blunts1498** [comment]
@thelinuxchoice Yes it is working for me now, thanks!
